name: tests

on:
  push:

jobs:
  flake8-pytest:
    strategy:
      fail-fast: false
      matrix:
        # python-version: [3.7, 3.8]
        python-version: [3.8]
        poetry-version: [1.1.2]
        # os: [ubuntu-18.04, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # - uses: actions/checkout@v2
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: microsoft/playwright-github-action@v1
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install packages
        run: |
          python -m pip install playwright
          poetry install  # --no-dev
          python -m playwright install chromium
      - name: Run flake8-pytest
        run: |
          poetry run flake8 --exit-zero
          poetry run pytest -k "test_version or google_tr"